version: "3"

services:
#GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true
    ports:
      - 3000:3000
    volumes:
      - ./config/custom.ini:/etc/grafana/custom.ini
      - grafana_data:/var/lib/grafana
      - ./logs:/var/log/grafana
      - ./grafana-simple-json-datasource:/var/lib/grafana/plugins/grafana-simple-json-datasource
      - ./csv_data:/var/lib/grafana/data/csv
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
#POSTGRES
  postgres:
    image: postgres:15.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
#PGADMIN
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 8080:80
volumes:
  grafana_data: {}
  postgres_data: {}
  pgadmin_data: {}
